spring:
  application:
    name: commerceplus
  cache:
    caffeine:
      spec: maximumSize=100,expireAfterWrite=300s

  datasource:
    url: jdbc:mysql://localhost:3306/commerceplus?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8080

portone:
  base-url: "https://api.portone.io"
  store-id: "store-82b5d935-d16d-45b1-a309-65042af5317d"
  channel-key: "channel-key-ca97e191-c472-436a-ac5a-c6bd4bfd24f8"
  api-secret: ${PORTONE_API_SECRET}

# JWT 설정
jwt:
  secret: "OONfMJx8azH6xrRzbhNGQ0JHkoNVNQS+N75QRNc8MGY="
  expiration: 3600000  # 1시간 (ms)
